version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
      SERVER_BASEPATH: "/kibana"
    ports:
      - 5601:5601
    networks:
      - elastic

  apm:
    image: docker.elastic.co/apm/apm-server:7.16.2
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
      KIBANA_HOST: "http://kibana:5601"
    ports:
      - 8200:8200
    networks:
      - elastic
    command: >
      apm-server -e 
      -E output.elasticsearch.hosts=$${ELASTICSEARCH_HOSTS}
      -E apm-server.rum.enabled=true
      -E apm-server.kibana.enabled=true 
      -E apm-server.kibana.host=$${KIBANA_HOST}

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
